disabled: false

ignore:
  - vulnerability: GHSA-5j98-mcp5-4vw2
    include-aliases: true
    reason: "glob upgraded to 10.5.0 in package.json, but Node.js 22.20.0-alpine3.22 is still using glob 10.4.5"
  - vulnerability: CVE-2025-9230
  - vulnerability: CVE-2025-9232
  - vulnerability: CVE-2025-9231
  - vulnerability: CVE-2025-60876
  - vulnerability: CVE-2025-59465
  - vulnerability: CVE-2025-55131
  - vulnerability: GHSA-r6q2-hw4h-h46w
  - vulnerability: GHSA-8qq5-rm4j-mr97
  - vulnerability: CVE-2025-55130
  - vulnerability: GHSA-xxjr-mmjv-4gpg
  - vulnerability: CVE-2026-21637
  - vulnerability: CVE-2025-59466
  - vulnerability: GHSA-g9mf-h72j-4rw9
  - vulnerability: CVE-2026-22796

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
